- menu_name: "服务"

- name: "联系我"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "订阅RSS"


- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
